env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: -1001595569305
    TG_TOKEN: ENCRYPTED[525a4d7e4426bdaad7b33b8a958d7baaba34378fa92a7e15408031fa8612387af7eb911ce3466cb4e57b8644e69ef7bf]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/xenontheinertg/docky:latest
      cpu: 8
      memory: 20G
      
  Clone_repo:
      - https://github.com/XenonTheInertG-CI/OrangeFox-CI

  Checks_script:
      - cd OrangeFox-CI
      - ./OrangeFox-CI/scripts/checks.sh

  Sync_script:
      - cd OrangeFox-CI
      - ./OrangeFox-CI/scripts/sync.sh

  Build_script:
      - cd OrangeFox-CI
      - ./OrangeFox-CI/scripts/build.sh

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - cd OrangeFox-CI
      - ./OrangeFox-CI/scripts/upload.sh
